-- Ürünler tablosu
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  price decimal(10,2),
  stock_quantity integer default 0,
  sales_count integer default 0
);

-- Satışlar tablosu (Opsiyonel ama önerilir)
create table if not exists sales (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id),
  quantity integer not null,
  total_amount decimal(10,2),
  sale_date timestamp with time zone default timezone('utc'::text, now())
);

-- RLS (Row Level Security) Politikalarını Aç (Güvenlik için)
alter table products enable row level security;
alter table sales enable row level security;

-- Okuma izni (Herkes okuyabilir)
create policy "Public products are viewable by everyone" 
on products for select using (true);

create policy "Public sales are viewable by everyone" 
on sales for select using (true);

-- Örnek veriler ekleyelim
insert into products (name, category, price, stock_quantity, sales_count) values
('Laptop X1', 'Elektronik', 25000.00, 45, 12),
('Kablosuz Kulaklık', 'Elektronik', 1500.00, 120, 50),
('Ergonomik Ofis Koltuğu', 'Mobilya', 4500.00, 20, 8),
('Filtre Kahve Makinesi', 'Mutfak', 1200.00, 35, 15),
('4K Monitör', 'Elektronik', 8000.00, 30, 20);
